using System;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Tmds.DBus.Protocol;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;


namespace Tmds.DBus.SourceGenerator;

public partial class DBusSourceGenerator
{
    private const string SignalHelperClass = """
                                             // <auto-generated/>
                                             using System;
                                             using System.Threading.Tasks;

                                             using Tmds.DBus.Protocol;

                                             #pragma warning disable
                                             #nullable enable
                                             namespace Tmds.DBus.SourceGenerator
                                             {
                                                 internal static class SignalHelper
                                                 {
                                                     public static ValueTask<IDisposable> WatchSignalAsync(Connection connection, MatchRule rule, Action<Exception?> handler, bool emitOnCapturedContext = true, ObserverFlags flags = ObserverFlags.None)
                                                         => connection.AddMatchAsync(rule, static (_, _) => null !, static (Exception? e, object _, object? _, object? handlerState) => ((Action<Exception?>)handlerState!).Invoke(e), null, handler, emitOnCapturedContext, flags);

                                                     public static ValueTask<IDisposable> WatchSignalAsync<T>(Connection connection, MatchRule rule, MessageValueReader<T> reader, Action<Exception?, T> handler, bool emitOnCapturedContext = true, ObserverFlags flags = ObserverFlags.None)
                                                         => connection.AddMatchAsync(rule, reader, static (e, arg, _, handlerState) => ((Action<Exception?, T>)handlerState!).Invoke(e, arg), null, handler, emitOnCapturedContext, flags);

                                                     public static ValueTask<IDisposable> WatchPropertiesChangedAsync<T>(Connection connection, string destination, string path, string @interface, MessageValueReader<PropertyChanges<T>> reader, Action<Exception?, PropertyChanges<T>> handler, bool emitOnCapturedContext = true, ObserverFlags flags = ObserverFlags.None)
                                                     {
                                                         MatchRule rule = new()
                                                         {
                                                             Type = MessageType.Signal,
                                                             Sender = destination,
                                                             Path = path,
                                                             Member = "PropertiesChanged",
                                                             Interface = "org.freedesktop.DBus.Properties",
                                                             Arg0 = @interface
                                                         };

                                                         return WatchSignalAsync(connection, rule, reader, handler, emitOnCapturedContext, flags);
                                                     }
                                                 }
                                             }
                                             """;

    private const string PropertyChangesClass = """
                                                // <auto-generated/>
                                                using System;

                                                #pragma warning disable
                                                #nullable enable
                                                namespace Tmds.DBus.SourceGenerator
                                                {
                                                    internal record PropertyChanges<TProperties>(TProperties Properties, string[] Invalidated, string[] Changed)
                                                    {
                                                        public bool HasChanged(string property) => Array.IndexOf(Changed, property) != -1;
                                                        public bool IsInvalidated(string property) => Array.IndexOf(Invalidated, property) != -1;
                                                    }
                                                }

                                                """;

    private const string DBusInterfaceHandlerInterface = """
                                                         // <auto-generated/>
                                                         using System;
                                                         using System.Threading.Tasks;

                                                         using Tmds.DBus.Protocol;

                                                         #pragma warning disable
                                                         #nullable enable
                                                         namespace Tmds.DBus.SourceGenerator
                                                         {
                                                             internal interface IDBusInterfaceHandler
                                                             {
                                                                 PathHandler? PathHandler { get; set; }

                                                                 Connection Connection { get; }

                                                                 ReadOnlySpan<byte> InterfaceName { get; }

                                                                 ReadOnlyMemory<byte> IntrospectXml { get; }

                                                                 void ReplyGetProperty(ReadOnlySpan<byte> name, MethodContext context);

                                                                 void ReplyGetAllProperties(MethodContext context);
                                                                 
                                                                 void SetProperty(ReadOnlySpan<byte> name, ref Reader reader);
                                                                 
                                                                 ValueTask ReplyInterfaceRequestAsync(MethodContext context);
                                                             }
                                                         }

                                                         """;

    private const string PathHandlerClass = """
                                            // <auto-generated/>
                                            using System.Collections.Generic;
                                            using System.Linq;
                                            using System.Threading.Tasks;

                                            using Tmds.DBus.Protocol;

                                            #pragma warning disable
                                            #nullable enable
                                            namespace Tmds.DBus.SourceGenerator
                                            {
                                                internal class PathHandler : IPathMethodHandler
                                                {
                                                    private readonly List<IDBusInterfaceHandler> _dbusInterfaces;

                                                    public PathHandler(string path)
                                                    {
                                                        Path = path;
                                                        _dbusInterfaces = new List<IDBusInterfaceHandler>();
                                                    }

                                                    /// <inheritdoc />
                                                    public string Path { get; }

                                                    /// <inheritdoc />
                                                    public bool HandlesChildPaths => false;

                                                    /// <inheritdoc />
                                                    public async ValueTask HandleMethodAsync(MethodContext context)
                                                    {
                                                        if (context.Request.Interface.SequenceEqual("org.freedesktop.DBus.Properties"u8))
                                                        {
                                                            if (context.Request.Member.SequenceEqual("Get"u8) && context.Request.Signature.SequenceEqual("ss"u8))
                                                            {
                                                                Reply();
                                                                void Reply()
                                                                {
                                                                    Reader reader = context.Request.GetBodyReader();
                                                                    ReadOnlySpan<byte> @interface = reader.ReadStringAsSpan();
                                                                    IDBusInterfaceHandler? handler = null;
                                                                    foreach (IDBusInterfaceHandler interfaceHandler in _dbusInterfaces)
                                                                    {
                                                                        if (interfaceHandler.InterfaceName.SequenceEqual(@interface))
                                                                        {
                                                                            handler = interfaceHandler;
                                                                            break;
                                                                        }
                                                                    }
                                                                    
                                                                    if (handler is null)
                                                                        return;

                                                                    ReadOnlySpan<byte> member = reader.ReadStringAsSpan();
                                                                    handler.ReplyGetProperty(member, context);
                                                                }
                                                            }
                                                            else if (context.Request.Member.SequenceEqual("GetAll"u8) && context.Request.Signature.SequenceEqual("s"u8))
                                                            {
                                                                Reply();
                                                                void Reply()
                                                                {
                                                                    Reader reader = context.Request.GetBodyReader();
                                                                    ReadOnlySpan<byte> @interface = reader.ReadStringAsSpan();
                                                                    IDBusInterfaceHandler? handler = null;
                                                                    foreach (IDBusInterfaceHandler interfaceHandler in _dbusInterfaces)
                                                                    {
                                                                        if (interfaceHandler.InterfaceName.SequenceEqual(@interface))
                                                                        {
                                                                            handler = interfaceHandler;
                                                                            break;
                                                                        }
                                                                    }
                                                                    
                                                                    if (handler is null)
                                                                        return;

                                                                    handler.ReplyGetAllProperties(context);
                                                                }
                                                            }
                                                            else if (context.Request.Member.SequenceEqual("Set"u8) && context.Request.Signature.SequenceEqual("ssv"u8))
                                                            {
                                                                Reply();
                                                                void Reply()
                                                                {
                                                                    Reader reader = context.Request.GetBodyReader();
                                                                    ReadOnlySpan<byte> @interface = reader.ReadStringAsSpan();
                                                                    IDBusInterfaceHandler? handler = null;
                                                                    foreach (IDBusInterfaceHandler interfaceHandler in _dbusInterfaces)
                                                                    {
                                                                        if (interfaceHandler.InterfaceName.SequenceEqual(@interface))
                                                                        {
                                                                            handler = interfaceHandler;
                                                                            break;
                                                                        }
                                                                    }
                                                                    
                                                                    if (handler is null)
                                                                        return;

                                                                    ReadOnlySpan<byte> member = reader.ReadStringAsSpan();
                                                                    handler.SetProperty(member, ref reader);
                                                                    if (!context.NoReplyExpected)
                                                                    {
                                                                        using MessageWriter writer = context.CreateReplyWriter(null);
                                                                        context.Reply(writer.CreateMessage());
                                                                    }
                                                                }
                                                            }
                                                        }
                                                        else if (context.Request.Interface.SequenceEqual("org.freedesktop.DBus.Introspectable"u8))
                                                        {
                                                            context.ReplyIntrospectXml(_dbusInterfaces.Select(static x => x.IntrospectXml).ToArray());
                                                        }
                                                        else
                                                        {
                                                            IDBusInterfaceHandler? handler = _dbusInterfaces.FirstOrDefault(x => x.InterfaceName.SequenceEqual(context.Request.Interface));
                                                            if (handler is not null)
                                                                await handler.ReplyInterfaceRequestAsync(context);
                                                        }
                                                    }

                                                    /// <inheritdoc />
                                                    public void Add(IDBusInterfaceHandler item)
                                                    {
                                                        item.PathHandler = this;
                                                        _dbusInterfaces.Add(item);
                                                    }

                                                    /// <inheritdoc />
                                                    public bool Contains(IDBusInterfaceHandler item) => _dbusInterfaces.Contains(item);

                                                    /// <inheritdoc />
                                                    public bool Remove(IDBusInterfaceHandler item)
                                                    {
                                                        item.PathHandler = null;
                                                        return _dbusInterfaces.Remove(item);
                                                    }

                                                    /// <inheritdoc />
                                                    public int Count => _dbusInterfaces.Count;
                                                }
                                            }
                                            """;

    private static MethodDeclarationSyntax MakeWriteNullableStringMethod() =>
        MethodDeclaration(
                PredefinedType(Token(SyntaxKind.VoidKeyword)),
                "WriteNullableString")
            .AddModifiers(
                Token(SyntaxKind.PublicKeyword),
                Token(SyntaxKind.StaticKeyword))
            .AddParameterListParameters(
                Parameter(
                        Identifier("writer"))
                    .WithType(
                        IdentifierName(nameof(MessageWriter)))
                    .AddModifiers(
                        Token(SyntaxKind.ThisKeyword),
                        Token(SyntaxKind.RefKeyword)),
                Parameter(
                        Identifier("value"))
                    .WithType(
                        NullableType(
                            PredefinedType(Token(SyntaxKind.StringKeyword)))))
            .WithExpressionBody(
                ArrowExpressionClause(
                    InvocationExpression(
                            MakeMemberAccessExpression("writer", nameof(MessageWriter.WriteString)))
                        .AddArgumentListArguments(
                            Argument(
                                BinaryExpression(
                                    SyntaxKind.CoalesceExpression,
                                    IdentifierName("value"),
                                    MakeMemberAccessExpression(nameof(String), nameof(string.Empty)))))))
            .WithSemicolonToken(
                Token(SyntaxKind.SemicolonToken));
}
