using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;


namespace Tmds.DBus.SourceGenerator;

internal static class DBusSourceGeneratorUtils
{
    internal static CompilationUnitSyntax MakeCompilationUnit(NamespaceDeclarationSyntax namespaceDeclaration) =>
        CompilationUnit()
            .AddUsings(
                UsingDirective(
                    IdentifierName("System")),
                UsingDirective(
                    IdentifierName("System.Collections.Generic")),
                UsingDirective(
                    IdentifierName("System.Linq")),
                UsingDirective(
                    IdentifierName("System.Runtime.InteropServices")),
                UsingDirective(
                    IdentifierName("System.Threading")),
                UsingDirective(
                    IdentifierName("System.Threading.Tasks")),
                UsingDirective(
                    IdentifierName("Microsoft.Win32.SafeHandles")),
                UsingDirective(
                    IdentifierName("Tmds.DBus.Protocol")))
            .WithLeadingTrivia(
                Comment("// <auto-generated>"))
            .AddMembers(namespaceDeclaration
                .WithLeadingTrivia(
                    TriviaList(
                        Trivia(
                            PragmaWarningDirectiveTrivia(
                                Token(SyntaxKind.DisableKeyword), true)),
                        Trivia(
                            NullableDirectiveTrivia(
                                Token(SyntaxKind.EnableKeyword), true)))))
            .NormalizeWhitespace();

    internal static FieldDeclarationSyntax MakeFieldDeclaration(string identifier, TypeSyntax type, params SyntaxToken[] modifiers) =>
        FieldDeclaration(
                VariableDeclaration(type)
                    .AddVariables(
                        VariableDeclarator(identifier)))
            .AddModifiers(modifiers);

    internal static FieldDeclarationSyntax MakePrivateReadOnlyField(string identifier, TypeSyntax type) =>
        MakeFieldDeclaration(identifier, type, Token(SyntaxKind.PrivateKeyword), Token(SyntaxKind.ReadOnlyKeyword));

    internal static PropertyDeclarationSyntax MakeGetOnlyProperty(TypeSyntax type, string identifier, params SyntaxToken[] modifiers) =>
        PropertyDeclaration(type, identifier)
            .AddModifiers(modifiers)
            .AddAccessorListAccessors(
                AccessorDeclaration(SyntaxKind.GetAccessorDeclaration)
                    .WithSemicolonToken(
                        Token(SyntaxKind.SemicolonToken)));

    internal static PropertyDeclarationSyntax MakeGetSetProperty(TypeSyntax type, string identifier, params SyntaxToken[] modifiers) =>
        PropertyDeclaration(type, identifier)
            .AddModifiers(modifiers)
            .AddAccessorListAccessors(
                AccessorDeclaration(SyntaxKind.GetAccessorDeclaration)
                    .WithSemicolonToken(
                        Token(SyntaxKind.SemicolonToken)),
                AccessorDeclaration(SyntaxKind.SetAccessorDeclaration)
                    .WithSemicolonToken(
                        Token(SyntaxKind.SemicolonToken)));

    internal static ExpressionStatementSyntax MakeAssignmentExpressionStatement(string left, string right) =>
        ExpressionStatement(
            MakeAssignmentExpression(
                IdentifierName(left),
                IdentifierName(right)));

    internal static AssignmentExpressionSyntax MakeAssignmentExpression(ExpressionSyntax left, ExpressionSyntax right) => AssignmentExpression(SyntaxKind.SimpleAssignmentExpression, left, right);

    internal static MemberAccessExpressionSyntax MakeMemberAccessExpression(string left, string right) => MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression, IdentifierName(left), IdentifierName(right));

    internal static MemberAccessExpressionSyntax MakeMemberAccessExpression(string left, string middle, string right) =>
        MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression, MakeMemberAccessExpression(left, middle), IdentifierName(right));

    internal static MemberAccessExpressionSyntax MakeMemberAccessExpression(string member1, string member2, string member3, string member4) =>
        MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression, MakeMemberAccessExpression(member1, member2, member3), IdentifierName(member4));

    internal static LiteralExpressionSyntax MakeLiteralExpression(string literal) => LiteralExpression(SyntaxKind.StringLiteralExpression, Literal(literal));

    internal static LiteralExpressionSyntax MakeLiteralExpression(int literal) => LiteralExpression(SyntaxKind.NumericLiteralExpression, Literal(literal));

    internal static LiteralExpressionSyntax MakeUtf8StringLiteralExpression(string literal) => LiteralExpression(SyntaxKind.StringLiteralExpression, Utf8Literal(literal));

    internal static TypeArgumentListSyntax MakeSingletonTypeArgumentList(SyntaxKind syntaxKind) => TypeArgumentList(
        SingletonSeparatedList<TypeSyntax>(
            PredefinedType(
                Token(syntaxKind))));

    internal static ArgumentListSyntax MakeSingletonArgumentList<T>(T argument) where T : ExpressionSyntax =>  ArgumentList(SingletonSeparatedList(Argument(argument)));

    private static SyntaxToken Utf8Literal(string value) =>
        Token(
            TriviaList(ElasticMarker),
            SyntaxKind.Utf8StringLiteralToken,
            SymbolDisplay.FormatLiteral(value, true) + "u8",
            value,
            TriviaList(ElasticMarker));
}
