namespace Tmds.DBus.SourceGenerator;

internal static class DBusSourceGeneratorClasses
{
    internal const string SignalHelperClass = """
                                             // <auto-generated/>
                                             using System;
                                             using System.Threading.Tasks;

                                             using Tmds.DBus.Protocol;

                                             #pragma warning disable
                                             #nullable enable
                                             namespace Tmds.DBus.SourceGenerator;

                                             internal static class SignalHelper
                                             {
                                                 public static ValueTask<IDisposable> WatchSignalAsync(DBusConnection connection, MatchRule rule, Action<Exception?> handler, bool emitOnCapturedContext = true, ObserverFlags flags = ObserverFlags.None)
                                                     => connection.AddMatchAsync(rule, static (_, _) => null !, static (Exception? e, object _, object? _, object? handlerState) => ((Action<Exception?>)handlerState!).Invoke(e), null, handler, emitOnCapturedContext, flags);

                                                 public static ValueTask<IDisposable> WatchSignalAsync<T>(DBusConnection connection, MatchRule rule, MessageValueReader<T> reader, Action<Exception?, T> handler, bool emitOnCapturedContext = true, ObserverFlags flags = ObserverFlags.None)
                                                     => connection.AddMatchAsync(rule, reader, static (e, arg, _, handlerState) => ((Action<Exception?, T>)handlerState!).Invoke(e, arg), null, handler, emitOnCapturedContext, flags);

                                                 public static ValueTask<IDisposable> WatchPropertiesChangedAsync<T>(DBusConnection connection, string destination, string path, string @interface, MessageValueReader<T> reader, Action<Exception?, T> handler, bool emitOnCapturedContext = true, ObserverFlags flags = ObserverFlags.None)
                                                 {
                                                     MatchRule rule = new()
                                                     {
                                                         Type = MessageType.Signal,
                                                         Sender = destination,
                                                         Path = path,
                                                         Member = "PropertiesChanged",
                                                         Interface = "org.freedesktop.DBus.Properties",
                                                         Arg0 = @interface
                                                     };

                                                     return WatchSignalAsync(connection, rule, reader, handler, emitOnCapturedContext, flags);
                                                 }
                                             }

                                             """;

    internal const string DBusInterfaceHandlerInterface = """
                                                         // <auto-generated/>
                                                         using System;
                                                         using System.Threading.Tasks;

                                                         using Tmds.DBus.Protocol;

                                                         #pragma warning disable
                                                         #nullable enable
                                                         namespace Tmds.DBus.SourceGenerator;

                                                         internal interface IDBusInterfaceHandler
                                                         {
                                                             PathHandler? PathHandler { get; set; }

                                                             DBusConnection Connection { get; }

                                                             ReadOnlySpan<byte> InterfaceName { get; }

                                                             ReadOnlyMemory<byte> IntrospectXml { get; }

                                                             void ReplyGetProperty(ReadOnlySpan<byte> name, MethodContext context);

                                                             void ReplyGetAllProperties(MethodContext context);
                                                             
                                                             void SetProperty(ReadOnlySpan<byte> name, ref Reader reader);
                                                             
                                                             ValueTask ReplyInterfaceRequestAsync(MethodContext context);
                                                         }

                                                         """;

    internal const string PathHandlerClass = """
                                            // <auto-generated/>
                                            using System.Collections.Generic;
                                            using System.Diagnostics.CodeAnalysis;
                                            using System.Linq;
                                            using System.Threading.Tasks;

                                            using Tmds.DBus.Protocol;

                                            #pragma warning disable
                                            #nullable enable
                                            namespace Tmds.DBus.SourceGenerator;

                                            internal class PathHandler(string path) : IPathMethodHandler
                                            {
                                                private readonly List<IDBusInterfaceHandler> _dbusInterfaces = [];

                                                /// <inheritdoc />
                                                public string Path { get; } = path;

                                                /// <inheritdoc />
                                                public bool HandlesChildPaths => false;

                                                /// <inheritdoc />
                                                public async ValueTask HandleMethodAsync(MethodContext context)
                                                {
                                                    if (context.IsPropertiesInterfaceRequest)
                                                    {
                                                        if (context.Request.Member.SequenceEqual("Get"u8) && context.Request.Signature.SequenceEqual("ss"u8))
                                                        {
                                                            Reply();
                                                            void Reply()
                                                            {
                                                                Reader reader = context.Request.GetBodyReader();
                                                                ReadOnlySpan<byte> @interface = reader.ReadStringAsSpan();
                                                                if (!TryFindHandler(@interface, out IDBusInterfaceHandler? handler))
                                                                    return;
                                                                
                                                                if (handler is null)
                                                                    return;

                                                                ReadOnlySpan<byte> member = reader.ReadStringAsSpan();
                                                                handler.ReplyGetProperty(member, context);
                                                            }
                                                        }
                                                        else if (context.Request.Member.SequenceEqual("GetAll"u8) && context.Request.Signature.SequenceEqual("s"u8))
                                                        {
                                                            Reply();
                                                            void Reply()
                                                            {
                                                                Reader reader = context.Request.GetBodyReader();
                                                                ReadOnlySpan<byte> @interface = reader.ReadStringAsSpan();
                                                                if (!TryFindHandler(@interface, out IDBusInterfaceHandler? handler))
                                                                    return;
                                                                
                                                                if (handler is null)
                                                                    return;

                                                                handler.ReplyGetAllProperties(context);
                                                            }
                                                        }
                                                        else if (context.Request.Member.SequenceEqual("Set"u8) && context.Request.Signature.SequenceEqual("ssv"u8))
                                                        {
                                                            Reply();
                                                            void Reply()
                                                            {
                                                                Reader reader = context.Request.GetBodyReader();
                                                                ReadOnlySpan<byte> @interface = reader.ReadStringAsSpan();
                                                                if (!TryFindHandler(@interface, out IDBusInterfaceHandler? handler))
                                                                    return;

                                                                ReadOnlySpan<byte> member = reader.ReadStringAsSpan();
                                                                handler.SetProperty(member, ref reader);
                                                                if (!context.NoReplyExpected)
                                                                {
                                                                    using MessageWriter writer = context.CreateReplyWriter(null);
                                                                    context.Reply(writer.CreateMessage());
                                                                }
                                                            }
                                                        }
                                                    }
                                                    else if (context.IsDBusIntrospectRequest)
                                                    {
                                                        context.ReplyIntrospectXml(_dbusInterfaces.Select(static x => x.IntrospectXml).ToArray());
                                                    }
                                                    else
                                                    {
                                                        IDBusInterfaceHandler? handler = _dbusInterfaces.FirstOrDefault(x => x.InterfaceName.SequenceEqual(context.Request.Interface));
                                                        if (handler is not null)
                                                            await handler.ReplyInterfaceRequestAsync(context);
                                                    }
                                                }

                                                /// <inheritdoc />
                                                public void Add(IDBusInterfaceHandler item)
                                                {
                                                    item.PathHandler = this;
                                                    _dbusInterfaces.Add(item);
                                                }

                                                /// <inheritdoc />
                                                public bool Contains(IDBusInterfaceHandler item) => _dbusInterfaces.Contains(item);

                                                /// <inheritdoc />
                                                public bool Remove(IDBusInterfaceHandler item)
                                                {
                                                    item.PathHandler = null;
                                                    return _dbusInterfaces.Remove(item);
                                                }

                                                /// <inheritdoc />
                                                public int Count => _dbusInterfaces.Count;

                                                private bool TryFindHandler(ReadOnlySpan<byte> @interface, [NotNullWhen(true)] out IDBusInterfaceHandler? handler)
                                                {
                                                    foreach (IDBusInterfaceHandler interfaceHandler in _dbusInterfaces)
                                                    {
                                                        if (interfaceHandler.InterfaceName.SequenceEqual(@interface))
                                                        {
                                                            handler = interfaceHandler;
                                                            return true;
                                                        }
                                                    }

                                                    handler = null;
                                                    return false;
                                                }
                                            }

                                            """;

    internal const string WriteNullableStringWriterExtension = """
                                                              // <auto-generated/>
                                                              using System.Collections.Generic;
                                                              using System.Linq;
                                                              using System.Threading.Tasks;

                                                              using Tmds.DBus.Protocol;

                                                              #pragma warning disable
                                                              #nullable enable
                                                              namespace Tmds.DBus.SourceGenerator;

                                                              internal static partial class WriterExtensions
                                                              {
                                                                  public static void WriteNullableString(this ref MessageWriter writer, string? value)
                                                                  {
                                                                      writer.WriteString(value ?? string.Empty);
                                                                  }
                                                              }

                                                              """;
}
